src/WLM/JuryToolBundle/Form/Type/RoundType.php
<?php
namespace WLM\JuryToolBundle\Form\Type;
use WLM\JuryToolBundle\Entity\Round;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormFactory;

class RoundType extends AbstractType
{

    private $formFactory;

    public function __construct(FormFactory $formFactory)
    {
        $this->formFactory = $formFactory;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $atleastWidget = $this->formFactory->create('number', null, array(
                'label' => 'Enter the minimum amount of jurors that must review each photo',
                'required' => false
        ));
        
        $builder->add('userMode', 'choice', array(
                'label' => "Select the type of jury for this round: ",
                'choices' => array(
                        Round::$ROUND_USER_MODE_OPEN => "Open",
                        Round::$ROUND_USER_MODE_INVITATIONAL => "Invitational"
                ),
                'multiple' => false,
                'expanded' => false
        ))
            ->add('scoringMode', 'choice', array(
                'label' => "Select the type of scoring for this round: ",
                'choices' => array(
                        Round::$ROUND_SCORING_MODE_BINARY => "Binary",
                        Round::$ROUND_SCORING_MODE_STARS => "Stars-based"
                ),
                'multiple' => false,
                'expanded' => false
        ))
            ->add('input', 'choice', array(
                'label' => "Select the input for this round",
                'choices' => array(
                        Round::$ROUND_INPUT_CATEGORY => "Commons category",
                        Round::$ROUND_INPUT_PLAINTEXT => "Plain text file"
                ),
                'multiple' => false,
                'expanded' => true
        ))
            ->add('scoringPolicy', new ComposedFieldType(), array(
                'label' => "What's the scoring policy of this round?",
                'choices' => array(
                        Round::$ROUND_SCORING_POLICY_ONE2ONE => "Every photo is scored by exactly one juror",
                        Round::$ROUND_SCORING_POLICY_ATLEAST => "Every photo is scored by at least some number of jurors"
                ),
                'subwidgets' => array(
                        Round::$ROUND_SCORING_POLICY_ONE2ONE => null,
                        Round::$ROUND_SCORING_POLICY_ATLEAST => $atleastWidget->createView()
                )
        ))
            ->add('canViewOtherVotes', 'checkbox', array(
                'label' => "Can a user view other users' votes?"
        ));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
                'data_class' => 'WLM\JuryToolBundle\Entity\Round'
        ));
    }

    public function getName()
    {
        return 'wlm_jurytoolbundle_roundtype';
    }
}

src/WLM/JuryToolBundle/Resources/views/Admin/imagelist.txt.twig
{% for i in imageList %}
{{ i.name|slice(5) }}
{% endfor %}

src/WLM/JuryToolBundle/Resources/views/Admin/round.html.twig
{% extends 'WLMJuryToolBundle::layout.html.twig' %}
{% block title %}{{ 'Administration Interface for Round %round%'|trans({ '%round%': round.id }) }}{% endblock %}
{% block content %}
{% if canRoundBeClosed %}
<div class="extrainfo">
<p>{{ 'According to the scoring policy of this round, this round can now be closed and you can <a href="%s">create a new round</a>.'|trans|format(path('wlm_jury_tool_config'))|raw }}</p> 
</div>
{% endif %}
{% block inputform %}
<p>
	<a href="{{ path('wlm_jury_tool_round', { 'id': round.id }) }}">{{ 'Start reviewing this round'|trans }}</a>
</p>
{% endblock %}
{% if users is not  null %}
<h2>{{ 'Jurors for this Round'|trans }}</h2>
{% if round.users is not empty %}
<ul>
	{% for user in round.users %}
	<li>{{ user.username }} &lt;{{ user.email }}&gt; <a href="{{ path('wlm_jury_tool_admin_export_user', { 'id': round.id, 'username': user.username }) }}">{{ stats[user.username]['total'] }}</a></li>
	{% endfor %}
</ul>
{% else %}
<div class="extrainfo">
<p>{{  'No jurors added to this round. Use the form below to add new jurors.'|trans }}</p>
</div>
{% endif %}
<h3>{{ 'Available Jurors'|trans }}</h3>
{% if users is not empty %}
<form action="{{ path('wlm_jury_tool_admin_acl', { 'id': round.id }) }}" method="post">
	<ul>
		{% for user in users %}
		<li><input name="userids[]" type="checkbox" value="{{ user.id }}"><label for="user_id">{{ user.email }}</label></li>
		{% endfor %}
	</ul>
	<br> <input type="submit" value="{{ 'Add Selected Jurors'|trans }}"></input>
</form>
{% else %}
<div class="extrainfo">
<p>{{  'No jurors available for this round. New jurors should <a href="%s">register</a> themselves to be listed in this form.'|trans|format(path('fos_user_registration_register'))|raw }}</p>
</div>
{% endif %}
{% endif %}
<h2>{{ 'Statistics'|trans }}</h2>
<p>
	Total number of photos: <a href="{{ path('wlm_jury_tool_admin_export', { 'id': round.id }) }}">{{ stats['numberOfPhotos'] }}</a>
</p>
{% if users %}
<ul>
	{% for user in round.users %}
	<li>{{ user.username }} &lt;{{ user.email }}&gt;
	<ul>
    {% if round.scoringMode == "stars" %}
	{% set cumulative = 0 %}
	{% for t in stats[user.username]['tally'] %}
	{% set cumulative = cumulative + t %}
	<li> {{ '%stars% stars:'|trans({ '%stars%': loop.index0 }) }} <a href="{{ path('wlm_jury_tool_admin_export_user_score', { 'id': round.id, 'username': user.username, 'score': loop.index0 }) }}">{{ t }}</a> ({{ 'cumulative:'|trans }} <a href="{{ path('wlm_jury_tool_admin_export_score', { 'id': round.id, 'score': '%s-'|format(loop.index0) }) }}">{{ cumulative }}</a>, {{ 'rest:'|trans }} <a href="{{ path('wlm_jury_tool_admin_export_score', { 'id': round.id, 'score': '%s+'|format(loop.index0) }) }}">{{ stats[user.username]['total'] - cumulative + t }}</a>)</li>
	{% endfor %}
	{% endif %}
    {% if round.scoringMode == "binary" %}
	{% for t in stats[user.username]['tally'] %}
	<li>{{ cycle(['No'|trans, 'Yes'|trans], loop.index0) }}: <a href="{{ path('wlm_jury_tool_admin_export_user_score', { 'id': round.id, 'username': user.username, 'score': loop.index0 }) }}">{{ t }}</a></li>
	{% endfor %}
	{% endif %}	
	</ul>
	</li>
	{% endfor %}
</ul>
{% endif %}
<ul>
    {% if round.scoringMode == "stars" %}
    {% set cumulative = 0 %}
	{% for t in stats['tally'] %}
	{% set cumulative = cumulative + t %}
	<li> {{ '%stars% stars:'|trans({ '%stars%': loop.index0 }) }} <a href="{{ path('wlm_jury_tool_admin_export_score', { 'id': round.id, 'score': loop.index0 }) }}">{{ t }}</a> ({{ 'cumulative:'|trans }} <a href="{{ path('wlm_jury_tool_admin_export_score', { 'id': round.id, 'score': '%s-'|format(loop.index0) }) }}">{{ cumulative }}</a>, {{ 'rest:'|trans }} <a href="{{ path('wlm_jury_tool_admin_export_score', { 'id': round.id, 'score': '%s+'|format(loop.index0) }) }}">{{ stats['total'] - cumulative + t }}</a>)</li>
	{% endfor %}
	{% endif %}
    {% if round.scoringMode == "binary" %}
	{% for t in stats['tally'] %}
	<li>{{ cycle(['No'|trans, 'Yes'|trans], loop.index0) }}: <a href="{{ path('wlm_jury_tool_admin_export_score', { 'id': round.id, 'score': loop.index0 }) }}">{{ t }}</a></li>
	{% endfor %}
	{% endif %}
</ul>
{% endblock %}

src/WLM/JuryToolBundle/Resources/views/Admin/roundfromcategory.html.twig
{% extends 'WLMJuryToolBundle:Admin:round.html.twig' %} {% block inputform %}
<form action="{{ path('wlm_jury_tool_admin_round_load', {'id': round.id}) }}" method="post">
    {% if app.session.hasFlash('error') %}
    <div class="errorinfo">
    {{ app.session.flash('error') }}
    </div>
    {% endif %}
	<label for="commonscat">{{ 'Specify the Wikimedia Commons category that will be used to load this round'|trans }}</label>
	<br>
	<input name="commonscat" size="100">
	<br>
	<input name="recurrent" id="recurrent" type="checkbox" value="1" /> <label for="recurrent">{{ 'Load images from this category on a daily basis?'|trans }}</label>
	<br>
	<input type="submit">
</form>
{% endblock %}

src/WLM/JuryToolBundle/Resources/views/Admin/roundfromplaintext.html.twig
{% extends 'WLMJuryToolBundle:Admin:round.html.twig' %}

{% block inputform %}
<form action="{{ path('wlm_jury_tool_admin_round_load', {'id': round.id}) }}" method="post" enctype="multipart/form-data">
<label for="plaintext">{{ 'Upload a plain text file containing one image name per line to specify the images for this round'|trans }}</label>
<br>
<input type="file" name="plaintext">
<br>
<input type="submit">
</form>
{% endblock %}

src/WLM/JuryToolBundle/Resources/views/Admin/roundfromprevious.html.twig
{% extends 'WLMJuryToolBundle:Admin:round.html.twig' %}

{% block inputform %}
<p>One very complex UI</p>
{% endblock %}